---

- name: Pi-hole | Copy lighttpd config
  template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
  notify: restart pihole_lighttpd
  when: pihole_web_server

- name: Pi-hole | Check current password hash
  command: grep -oP 'WEBPASSWORD=\K\w+' /etc/pihole/setupVars.conf
  changed_when: false
  ignore_errors: true
  register: pihole_current_password_hash

- name: Pi-hole | Set password
  command: "pihole -a -p {{ pihole_password }}"
  changed_when: true
  when: pihole_password | length > 0 and
        pihole_password | hash('sha256') | hash('sha256') != pihole_current_password_hash.stdout
