---

- name: Pi-hole | Copy lighttpd config
  template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
  notify: restart pihole_lighttpd
  when: pihole_web_server

- name: Pi-hole | Set password
  command: "pihole -a -p {{ pihole_password }}"
  when: pihole_password | length > 0
