---

- name: Install dependencies
  apt:
    name: "{{ pihole_required_packages }}"
    state: present
    update-cache: yes

- name: Ensure config path
  file:
    dest: /etc/pihole
    state: directory

- name: Copy setup vars
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf

- name: Download install script
  get_url:
    url: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
    dest: /tmp/pihole-install.sh
    mode: 0755

- name: Run install script
  command: /tmp/pihole-install.sh --unattended
  changed_when: true
