---

- name: Pi-hole | Check installation
  command: pihole version
  register: pihole_version_check
  ignore_errors: true
  changed_when: false

- name: Pi-hole | Install
  include: install.yml
  when: pihole_version_check is failed or pihole_force_reinstall
  tags:
    - pihole_install

- name: Pi-hole | Configure
  include: config.yml
  tags:
    - pihole_configure
